# Generated by Django 5.1.4 on 2024-12-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_app/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(choices=[('pinch', 'Pinch'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon'), ('cup', 'Cup'), ('ounce', 'Ounce'), ('pound', 'Pound'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('liter', 'Liter'), ('piece', 'Piece'), ('dash', 'Dash'), ('handful', 'Handful'), ('slice', 'Slice'), ('clove', 'Clove')], max_length=20)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('season', 'Season'), ('taste', 'Taste'), ('time', 'Time'), ('complexity', 'Complexity'), ('cuisine', 'Cuisine'), ('diet', 'Diet')], max_length=20)),
                ('recipes', models.ManyToManyField(related_name='tags', to='main_app.recipe')),
            ],
        ),
    ]
