# Generated by Django 5.1.4 on 2024-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main_app.recipe'),
        ),
    ]
