# Generated by Django 5.1.4 on 2024-12-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tag_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
    ]
