# Generated by Django 5.1.4 on 2024-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main_app.tag'),
        ),
    ]
