# Generated by Django 5.1.4 on 2024-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_tag_recipes_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('pinch', 'Pinch'), ('dash', 'Dash'), ('drop', 'Drop'), ('smidgen', 'Smidgen'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon'), ('cup', 'Cup'), ('fluid_ounce', 'Fluid Ounce'), ('ounce', 'Ounce'), ('pound', 'Pound'), ('milligram', 'Milligram'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('milliliter', 'Milliliter'), ('centiliter', 'Centiliter'), ('deciliter', 'Deciliter'), ('liter', 'Liter'), ('quart', 'Quart'), ('pint', 'Pint'), ('gallon', 'Gallon'), ('piece', 'Piece'), ('slice', 'Slice'), ('clove', 'Clove'), ('stick', 'Stick'), ('stalk', 'Stalk'), ('leaf', 'Leaf'), ('head', 'Head'), ('handful', 'Handful'), ('bunch', 'Bunch'), ('sprig', 'Sprig'), ('cube', 'Cube'), ('can', 'Can'), ('jar', 'Jar'), ('bottle', 'Bottle'), ('bag', 'Bag'), ('pack', 'Pack'), ('box', 'Box'), ('bar', 'Bar'), ('sheet', 'Sheet'), ('square', 'Square'), ('ring', 'Ring'), ('roll', 'Roll'), ('envelope', 'Envelope'), ('ball', 'Ball'), ('round', 'Round'), ('log', 'Log'), ('pat', 'Pat'), ('fillet', 'Fillet'), ('steak', 'Steak'), ('rib', 'Rib'), ('chop', 'Chop'), ('drumstick', 'Drumstick'), ('wing', 'Wing'), ('thigh', 'Thigh'), ('whole', 'Whole'), ('quart', 'Quart'), ('bundle', 'Bundle'), ('slice', 'Slice'), ('portion', 'Portion'), ('serving', 'Serving')], max_length=20),
        ),
    ]
