# Generated by Django 5.1.3 on 2024-12-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241206_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('dietary', 'Dietary'), ('season', 'Season'), ('time', 'Time'), ('cuisine', 'Cuisine'), ('flavor', 'Flavor')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
