# Generated by Django 5.1.3 on 2024-12-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(choices=[('unit', 'Unit'), ('ounce', 'Ounce'), ('cup', 'Cup'), ('lb', 'Pound'), ('kg', 'Kilogram'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('ml', 'Milliliter'), ('liter', 'Liter'), ('piece', 'Piece'), ('pinch', 'Pinch')], max_length=50),
        ),
    ]
